"""Add User

Revision ID: 7f8010c378c3
Revises: 842c65052781
Create Date: 2026-02-20 14:06:26.172154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f8010c378c3'
down_revision = '842c65052781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(length=300), nullable=False))
        batch_op.drop_column('content')

    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('done')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('done', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.VARCHAR(length=300), nullable=False))
        batch_op.drop_column('message')

    # ### end Alembic commands ###
